name: Reproducer
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    win:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12
            - name: Install dependencies
              shell: bash
              run: |
                  pip install poetry
                  poetry install
                  poetry run pytest -nauto test1.py -vvs
